programs     := test
sources      := test.cpp ../PF_HashTable.cpp
libraries    :=
extra_clean  :=

modules      :=
include_dirs := ../../PF ../../Main

test: test.o ../PF_HashTable.o

include ../../Makefile.mk
